{
 "title": "histogram db",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_usage[1m]) <= 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_request_total{path!~\"/metrics|/metrics/\"}[30s])) by (method, path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries Per Second (QPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(db_request_duration_seconds_bucket[1m])) by (operation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_request_duration_seconds_bucket[5m])) by (le, operation))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum(irate(\r\n            http_request_duration_seconds_count{ path !~ \"/metrics|/metrics/\"}\r\n            [1m]\r\n            )\r\n        ) by (method)) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Execution Time Histogram",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_request_duration_seconds_bucket[5m])) by (le, query_type))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (le, method, path))",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}