name: prometheus-monitoring-v05
services:
    prometheus:
      image: docker.io/prom/prometheus:v3.1.0 # Changed to 'latest' for simplicity or specify a desired version
      container_name: prometheus-v05
      ports:
        - 9090:9090
      command: "--config.file=/etc/prometheus/prometheus.yaml --storage.tsdb.path=/prometheus" # Added storage path
      volumes:
        - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
        - prometheus:/prometheus
      restart: unless-stopped
      networks:
        - monitoring-network

    grafana:
      image: docker.io/grafana/grafana-oss:11.5.1
      container_name: grafana-v05
      ports:
        - "3000:3000"
      volumes:
        - grafana:/var/lib/grafana
      restart: unless-stopped
      networks:
        - monitoring-network

    # node-exporter:
    #   image: prom/node-exporter:latest
    #   container_name: node-exporter-v05
    #   ports:
    #     - "9100:9100"
    #   restart: unless-stopped
    #   networks:
    #     - monitoring-network
    #   volumes:
    #     - /proc:/host/proc:ro
    #     - /sys:/host/sys:ro
    #     - /:/rootfs:ro
    #   command:
    #     - '--path.procfs=/host/proc'
    #     - '--path.sysfs=/host/sys'
    #     - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($|/)"'

    # cadvisor:
    #   image: gcr.io/cadvisor/cadvisor:latest
    #   container_name: cadvisor-v05
    #   ports:
    #     - 8080:8080
    #   volumes:
    #     - /:/rootfs:ro
    #     - /run:/run:ro
    #     - /sys:/sys:ro
    #     - /var/lib/docker/:/var/lib/docker:ro
    #     - /dev/disk/:/dev/disk:ro
    #   devices:
    #     - /dev/kmsg
    #   privileged: true
    #   restart: unless-stopped
    #   networks:
    #     - monitoring-network
    #   depends_on: ["sentiment-analysis"]

    sentiment-analysis:
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: sentiment-analysis-server-v05
      ports:
        - "8000:8000"
      env_file:
      - .env
      networks:
        - monitoring-network
      depends_on:
        - loki

    loki:
      image: grafana/loki:latest
      container_name: loki-v05
      volumes:
        - ./configs/loki.yaml:/etc/loki/config.yaml:ro
        - data_loki:/loki:rw
      ports:
        - "3100:3100"
      restart: unless-stopped
      networks:
        - monitoring-network

volumes:
  prometheus:
  grafana:
  data_loki:
    driver: local

networks:
  monitoring-network:
    driver: bridge
