{
 "title": "2st Test",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request/Response Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(rate(request_size_bytes_sum[5m]) / rate(request_size_bytes_count[5m]))",
     "legendFormat": "Request"
    },
    {
     "expr": "avg(rate(response_size_bytes_sum[5m]) / rate(response_size_bytes_count[5m]))",
     "legendFormat": "Response"
    }
   ]
  },
  {
   "title": "Request/Response size Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(request_size_bytes_bucket[$__rate_interval]))",
     "legendFormat": "Request"
    },
    {
     "expr": "histogram_quantile(0.95, rate(response_size_bytes_bucket[$__rate_interval]))",
     "legendFormat": "Response"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_total{instance=\"sentiment-analysis:8000\", path!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_total{instance=\"sentiment-analysis:8000\", path!=\"/metrics\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Client Request Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{status=\"200\", path!~\"/metrics\"}[30s])) by (le))",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Requests Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{path!~\"/metrics|/metrics/\"}[30s]))",
     "legendFormat": "Traffic"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(3, http_request_duration_seconds_sum{path!~\"/metrics\"} / http_request_duration_seconds_count{path!~\"/metrics\"})",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_request_total{instance=\"sentiment-analysis:8000\", path!~\"/metrics\"}[1m])",
     "legendFormat": "{{method}}{{path}}"
    }
   ]
  },
  {
   "title": "P99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(http_request_duration_seconds_bucket{instance=\"sentiment-analysis:8000\", path!=\"/metrics\"}[$__rate_interval])) by(path, method, le))",
     "legendFormat": "{{method}}{{path}}"
    }
   ]
  },
  {
   "title": "P90 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.90,sum(rate(http_request_duration_seconds_bucket{instance=\"sentiment-analysis:8000\", path!=\"/metrics\"}[$__rate_interval])) by(path, method, le))",
     "legendFormat": "{{method}}{{path}}"
    }
   ]
  },
  {
   "title": "P50 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.50,sum(rate(http_request_duration_seconds_bucket{instance=\"sentiment-analysis:8000\", path!=\"/metrics\"}[$__rate_interval])) by(path, method, le))",
     "legendFormat": "{{method}}{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_total{status=\"200\", path=~\"/metrics\"}[60m])) / sum(rate(http_request_total{path=~\"/metrics\"}[60m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 4xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_total{status=\"404\"}[60m])) / sum(rate(http_request_total[60m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries Per Second (QPS)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(db_request_duration_seconds_count{}[$__rate_interval]) )",
       "legendFormat": "QPS"
      }
     ]
    },
    {
     "title": "Database Insert Latency (p90)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(db_request_duration_seconds_bucket{}[30s])) by (le, operation))",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 37 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{severity=\"error\"}"
    }
   ]
  },
  {
   "title": "Info and others",
   "type": "logs",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 37 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{application=\"fastapi\",severity!=\"error\"}"
    }
   ]
  },
  {
   "title": "Total number of logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 37 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({application=\"fastapi\" ,severity != \"\"} [$__auto])) by (severity)"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage Hardcoded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "avg(process_cpu_usage{} )", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Revise1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database Connections",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (group) (pg_stat_activity_count{usename=\"node\"})",
       "legendFormat": "Node"
      },
      {
       "expr": "sum by (group) (pg_stat_activity_count{usename=\"bun\"})",
       "legendFormat": "Bun"
      },
      {
       "expr": "sum by (group) (pg_stat_activity_count{usename=\"deno\"})",
       "legendFormat": "Deno"
      }
     ]
    },
    {
     "title": "PostgreSQL CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=\"postgresql.antonputra.pvt:9100\",mode=\"idle\"}[30s])) * 100)",
       "legendFormat": "MongoDB"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(container_cpu_cfs_throttled_seconds_total{container_label_io_kubernetes_container_name=\"node-app\"}[30s]))",
       "legendFormat": "Node"
      },
      {
       "expr": "avg(rate(container_cpu_cfs_throttled_seconds_total{container_label_io_kubernetes_container_name=\"bun-app\"}[30s]))",
       "legendFormat": "Bun"
      },
      {
       "expr": "avg(rate(container_cpu_cfs_throttled_seconds_total{container_label_io_kubernetes_container_name=\"deno-app\"}[30s]))",
       "legendFormat": "Deno"
      }
     ]
    },
    {
     "title": "Availability",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"node-client\",\n            status!~\"[4-5].*\"\n        }[30s])) by (container) /\nsum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"node-client\"\n        }[30s])) by (container)",
       "legendFormat": "Node"
      },
      {
       "expr": "sum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"bun-client\",\n            status!~\"[4-5].*\"\n        }[30s])) by (container) /\nsum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"bun-client\"\n        }[30s])) by (container)",
       "legendFormat": "Bun"
      },
      {
       "expr": "sum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"deno-client\",\n            status!~\"[4-5].*\"\n        }[30s])) by (container) /\nsum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"deno-client\"\n        }[30s])) by (container)",
       "legendFormat": "Deno"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(container_memory_working_set_bytes\n{\n    container_label_io_kubernetes_container_name=\"node-app\"\n} /\ncontainer_spec_memory_limit_bytes\n{\n    container_label_io_kubernetes_container_name=\"node-app\"\n})",
       "legendFormat": "Node"
      },
      {
       "expr": "avg(container_memory_working_set_bytes\n{\n    container_label_io_kubernetes_container_name=\"bun-app\"\n} /\ncontainer_spec_memory_limit_bytes\n{\n    container_label_io_kubernetes_container_name=\"bun-app\"\n})",
       "legendFormat": "Bun"
      },
      {
       "expr": "avg(container_memory_working_set_bytes\n{\n    container_label_io_kubernetes_container_name=\"deno-app\"\n} /\ncontainer_spec_memory_limit_bytes\n{\n    container_label_io_kubernetes_container_name=\"deno-app\"\n})",
       "legendFormat": "Deno"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(sum(\n    rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_container_name=\"node-app\"}[30s]))\nby (\n    container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name) /\nsum(\n    container_spec_cpu_quota{container_label_io_kubernetes_container_name=\"node-app\"} /\n    container_spec_cpu_period{container_label_io_kubernetes_container_name=\"node-app\"}\n    ) \nby (container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name))",
       "legendFormat": "Node"
      },
      {
       "expr": "avg(sum(\n    rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_container_name=\"bun-app\"}[30s]))\nby (\n    container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name) /\nsum(\n    container_spec_cpu_quota{container_label_io_kubernetes_container_name=\"bun-app\"} /\n    container_spec_cpu_period{container_label_io_kubernetes_container_name=\"bun-app\"}\n    ) \nby (container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name))",
       "legendFormat": "Bun"
      },
      {
       "expr": "avg(sum(\n    rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_container_name=\"deno-app\"}[30s]))\nby (\n    container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name) /\nsum(\n    container_spec_cpu_quota{container_label_io_kubernetes_container_name=\"deno-app\"} /\n    container_spec_cpu_period{container_label_io_kubernetes_container_name=\"deno-app\"}\n    ) \nby (container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name))",
       "legendFormat": "Deno"
      }
     ]
    }
   ]
  }
 ]
}