{
 "title": "2st Test",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Queries Per Second (QPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(db_request_duration_seconds_count{}[$__rate_interval]) )",
     "legendFormat": "${metric} (overall per-second rate)"
    }
   ]
  },
  {
   "title": "Requests Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{path!~\"/metrics|/metrics/\"}[30s]))",
     "legendFormat": "Traffic"
    }
   ]
  },
  {
   "title": "PostgreSQL CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=\"postgresql.antonputra.pvt:9100\",mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "MongoDB"
    }
   ]
  },
  {
   "title": "Percent of 4xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_total{status=\"404\"}[60m])) / sum(rate(http_request_total[60m]))",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "http_requests_total{status=\"4xx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes\n{\n    container_label_io_kubernetes_container_name=\"node-app\"\n} /\ncontainer_spec_memory_limit_bytes\n{\n    container_label_io_kubernetes_container_name=\"node-app\"\n})",
     "legendFormat": "Node"
    },
    {
     "expr": "avg(container_memory_working_set_bytes\n{\n    container_label_io_kubernetes_container_name=\"bun-app\"\n} /\ncontainer_spec_memory_limit_bytes\n{\n    container_label_io_kubernetes_container_name=\"bun-app\"\n})",
     "legendFormat": "Bun"
    },
    {
     "expr": "avg(container_memory_working_set_bytes\n{\n    container_label_io_kubernetes_container_name=\"deno-app\"\n} /\ncontainer_spec_memory_limit_bytes\n{\n    container_label_io_kubernetes_container_name=\"deno-app\"\n})",
     "legendFormat": "Deno"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_total{status=\"200\"}[60m])) / sum(rate(http_request_total[60m]))",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "rate(http_requests_total{status=\"2xx\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_cfs_throttled_seconds_total{container_label_io_kubernetes_container_name=\"node-app\"}[30s]))",
     "legendFormat": "Node"
    },
    {
     "expr": "avg(rate(container_cpu_cfs_throttled_seconds_total{container_label_io_kubernetes_container_name=\"bun-app\"}[30s]))",
     "legendFormat": "Bun"
    },
    {
     "expr": "avg(rate(container_cpu_cfs_throttled_seconds_total{container_label_io_kubernetes_container_name=\"deno-app\"}[30s]))",
     "legendFormat": "Deno"
    }
   ]
  },
  {
   "title": "Client Request Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{status=\"200\"}[30s])) by (le))",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Database Insert Latency (p90)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_request_duration_seconds_bucket{operation=\"select_device\"}[30s])) by (le))",
     "legendFormat": "Select"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_request_duration_seconds_bucket{operation=\"insert_device\"}[30s])) by (le))",
     "legendFormat": "Insert"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum(\n    rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_container_name=\"node-app\"}[30s]))\nby (\n    container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name) /\nsum(\n    container_spec_cpu_quota{container_label_io_kubernetes_container_name=\"node-app\"} /\n    container_spec_cpu_period{container_label_io_kubernetes_container_name=\"node-app\"}\n    ) \nby (container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name))",
     "legendFormat": "Node"
    },
    {
     "expr": "avg(sum(\n    rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_container_name=\"bun-app\"}[30s]))\nby (\n    container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name) /\nsum(\n    container_spec_cpu_quota{container_label_io_kubernetes_container_name=\"bun-app\"} /\n    container_spec_cpu_period{container_label_io_kubernetes_container_name=\"bun-app\"}\n    ) \nby (container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name))",
     "legendFormat": "Bun"
    },
    {
     "expr": "avg(sum(\n    rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_container_name=\"deno-app\"}[30s]))\nby (\n    container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name) /\nsum(\n    container_spec_cpu_quota{container_label_io_kubernetes_container_name=\"deno-app\"} /\n    container_spec_cpu_period{container_label_io_kubernetes_container_name=\"deno-app\"}\n    ) \nby (container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name))",
     "legendFormat": "Deno"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"node-client\",\n            status!~\"[4-5].*\"\n        }[30s])) by (container) /\nsum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"node-client\"\n        }[30s])) by (container)",
     "legendFormat": "Node"
    },
    {
     "expr": "sum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"bun-client\",\n            status!~\"[4-5].*\"\n        }[30s])) by (container) /\nsum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"bun-client\"\n        }[30s])) by (container)",
     "legendFormat": "Bun"
    },
    {
     "expr": "sum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"deno-client\",\n            status!~\"[4-5].*\"\n        }[30s])) by (container) /\nsum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"deno-client\"\n        }[30s])) by (container)",
     "legendFormat": "Deno"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (group) (pg_stat_activity_count{usename=\"node\"})",
     "legendFormat": "Node"
    },
    {
     "expr": "sum by (group) (pg_stat_activity_count{usename=\"bun\"})",
     "legendFormat": "Bun"
    },
    {
     "expr": "sum by (group) (pg_stat_activity_count{usename=\"deno\"})",
     "legendFormat": "Deno"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "avg(container_threads{container_label_io_kubernetes_container_name=\"bun-app\"})",
     "legendFormat": "Bun"
    },
    {
     "expr": "avg(container_threads{container_label_io_kubernetes_container_name=\"node-app\"})",
     "legendFormat": "Node"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "tester_active_clients", "legendFormat": "{{container}}" }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total[30s]) * 8",
     "legendFormat": "Python (Receive)"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{container_label_app=\"django-app\"}[30s]) * 8",
     "legendFormat": "Python (Transmit)"
    },
    {
     "expr": "irate(container_network_receive_bytes_total{container_label_app=\"go-app\"}[30s]) * 8",
     "legendFormat": "Go (Receive)"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{container_label_app=\"go-app\"}[30s]) * 8",
     "legendFormat": "Go (Transmit)"
    }
   ]
  }
 ]
}